/* eslint-disable */
export const initialState = {
    stompClient: null,
    chatClient: null,
    sellStompClient: null,
    buyStompClient: null,
    access_token: '',
    sellOffersQueue: null,
    buyOffersQueue: null,
    username: null,
    paymentFilters: [],
    fingerprint: null,
    uuid: '',
    cartItems: [],
    user: null,
    kycStatus: null,
    pendingSellOrder: null,
    pendingBuyOrder: null,
    chatId: '',
    chat: null,
};
